before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: vvDvShUYl73z9lfHElfZFRFfVHVccBx8STjCjcd7zO5JgrOR0CLZw9aDKLNaIk7V/XHFN/mE6yBcOmtGXh5J5Mu2iJQRu3IzDK1/6eCeFPxzdCh+kfjSlrYj5GwJL8Y2xpZMwgrp88D9MHo8Oa6sOFOfQaBibigpl4WOgMFMai8XDG4eQevEyEEypCLLoS73GDHT7yw5dYBWAC+ZnNSS5vpblfjc6hqnH6/ueY7nO4sKfnYW2Mz7tWblt2rNeJOl/73gnxgMDyzhRV4uu5hVFwwJ30zQUc5cNZ3AiypDxlo/d8/Ka7UjeAyOfKepveNv/o5E9jb/xOo9ehtoh7z7jGMmHH2YAf7zjjmKrVPbKXBLTkuy8k126XjhufJZeTvaLkSDC4wSz9EI5PuIIr0CdVL0yhrGtQXwWktNJ1V129LLKE6c5w/GGB1tnokekFWj+JX2jYDsl9T+KI/mVnKeAOgPVqSkRGGtcjsfDztLI+ne1OOccNf9EjSFWLlbS/DgqxSDajL+BOVT2l/kKfuBXSELV6ChvugMjlbCRDyI35RkoP3Bs+oCcLrbEtFF3D7uZcIzolm4RbwvfzNUrHYNklG+jODZIN4RGEgyFOftVNd+Psntq/VH8U7PFaz9vZsYl78u/aQGeCyPEcZS1guaxar81gaOfoWsabiJJH9Wh60= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
